version: 2

sources:
  - name: plantmonitordb
    schema: public
    tables:
      - name: alarm_status
      - name: alarm
      - name: alarm_historic
      - name: meter
      - name: meterregistry
      - name: plant
      - name: solarevent
      - name: satellite_readings
        columns:
          - name: time
            description: timestamp del registre
          - name: plant
            description: id de la planta
          - name: global_horizontal_irradiation_wh_m2
            description: irradiació global horitzontal en wh/m2
          - name: global_tilted_irradiation_wh_m2
            description: irradiació global inclinada en wh/m2
          - name: module_temperature_dc
            description: temperatura del mòdul en ºC
          - name: photovoltaic_energy_output_wh
            description: sortida d'energia fotovoltaica en wh
          - name: source
            description: font d'on s'ha obtingut la lectura
          - name: request_time
            description: timestamp de quan es va fer la sol·licitud de dades
      - name: forecast
      - name: forecastmetadata
      - name: forecastpredictor
      - name: forecastvariable
      - name: sensorirradiationregistry
      - name: plantmoduleparameters
      - name: sensor
      - name: view_hd_daily
      - name: view_satellite_irradiation
      - name: plantparameters
      - name: inverter
      - name: inverterregistry
      - name: string
      - name: stringregistry
      - name: irradiationregistry
  - name: plantlake
    schema: airbyte_imported
    tables:
      - name: modbus_readings
      - name: omie_historical_price_hour
        description: >
          Taula importada via airbyte del projecte de KPIs antic.
  - name: lake
    schema: lake
    tables:
      - name: modbus_readings
        description: >
          Lectures crues inserides pel DAG d'ingesta que llegeix directament
          els dispositius de planta utilitzant modbus a
          través del router de la planta
      - name: dset_responses
        description: >
          Lectures crues inserides pel DAG d'ingesta que llegeix directament
          l'API de DSET que ofereix lectures remotes de les plantes de SomEnergia.
          S'escriuen en base de dades en format JSONB recollint el JSON cru
          de la API de DSET.

models:
  - name: view_inverter_metrics_daily
    description: "TO BE DEPRECATED extended metrics of inverterregistry"

  - name: view_q_monthly
    description: "energy import/export and q import/export by month, by plant"

  - name: view_availability
    description: "availability (ht hours('ht' = hour with satellite irradiation bigger than 5 wh/m2) / hd hours ('hd' = hour with production bigger than 0.7/hour)) by day, by plant"

  - name: view_cos_phi_monthly
    description: "Relation between export-import energy and capacitive-inductive power"

  - name: view_expected_power
    description: "Given a probe irradiation, what would be the expected power output"

  - name: view_hd_daily
    description: "Count hours hd ('hd' = hour with production bigger than 0.7/hour),  by plant"

  - name: view_ht_daily
    description: "Count hours ht ('ht' = hour with satellite irradiation bigger than 5 wh/m2) by day , by plant"

  - name: view_ht_monthly
    description: "Count hours ht ('ht' = hour with  satellite irradiation bigger than 5 wh/m2), by month, by plant"

  - name: view_pr_hourly
    description: "export energy, irradiation and performance ratio (pr), hourly, by plant"

  - name: view_target_energy
    description: "monthly alcolea energy production target"

  - name: view_satellite_irradiation
    description: "satellite irradiation readings in wh_m2, hourly, by plant"


  - name: best_forecast
    description: best forecast hour for each forecast - which is the previous day's if available -