version: 2

sources:
  - name: plantmonitor
    schema: public
    tables:
      - name: alarm_status
      - name: alarm
      - name: alarm_historic
      - name: meter
      - name: meterregistry
      - name: plant
      - name: solarevent
      - name: satellite_readings
      - name: forecast
      - name: forecastmetadata
      - name: forecastpredictor
      - name: forecastvariable

models:

  - name: alarm_meter_no_energy
    description: "Cleaned alarm model"
    columns:
      - name: create_date
        description: "alarm create date"
        tests:
          - not_null