version: 2

sources:
  - name: plantmonitor
    schema: public
    tables:
      - name: alarm_status
      - name: alarm
      - name: alarm_historic
      - name: meter
      - name: meterregistry
      - name: plant
      - name: solarevent
      - name: satellite_readings

models:

  - name: alarms_model
    description: "Cleaned alarm model"
    config:
      schema: prod
    columns:
      - name: create_date
        description: "alarm create date"
        tests:
          - not_null