# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_jardiner"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_jardiner"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_jardiner:
    # Config indicated by + and applies to all files under models/example/
    jardiner:
      +materialized: view
      +tags: jardiner
      raw:
        +docs:
          node_color: "#d17f4c"
        dset:
          +tags: dset
        simel:
          +grants:
            select: ['mercat_electric']
      intermediate:
        +docs:
          node_color: "#d05808"
        dset:
          +tags: dset
        simel:
          +grants:
            select: ['mercat_electric']
      marts:
        +docs:
          node_color: "goldenrod"
        dset:
          +tags: dset
        simel:
          +grants:
            select: ['mercat_electric']
      observability:
        +docs:
          node_color: "#c3c557"
        dset:
          +tags: dset
    legacy:
      +tags: legacy
      operational:
        +docs:
          node_color: "#f0cc97"
        +materialized: view
        +grants:
          select: "opendata"
  ## see docs: https://docs.elementary-data.com/
  elementary:
    ## elementary models will be created in the schema '<your_schema>_elementary'
    +schema: "elementary"
    +docs:
      node_color: "pink"
    ## To disable elementary for dev, uncomment this:
    # enabled: "{{ target.name in ['prod','analytics'] }}"

  re_data:
    +docs:
      show: false
      node_color: "lightblue"

snapshots:
  +docs:
    node_color: "#e7bca1"

tests:
  +docs:
    node_color: "#84b4bc"

seeds:
  dbt_jardiner:
    jardiner:
      +tags: jardiner
    legacy:
      +tags: legacy

