---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: trailing-whitespace
      - id: detect-private-key
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.6.3"
    hooks:
      - id: ruff
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.1
    hooks:
      # enable sqlfluff-fix will modify sql files.
      - id: sqlfluff-fix
        additional_dependencies: ["dbt-postgres", "sqlfluff-templater-dbt"]
      - id: sqlfluff-lint
        additional_dependencies: ["dbt-postgres", "sqlfluff-templater-dbt"]
fail_fast: false
files: ".*"
exclude: |
  (?x)^(
      desktop.ini
  )$
