---
name: somenergia-jardiner

x-repo-common:
  volumes: &repo-common-volumes
    "./:/repo" # mount current directory at /app

x-dbt-common:
  # reusable bits, see https://docs.docker.com/compose/compose-file/10-fragments/
  environment: &dbt-common-env # needed for ~/.dbt/profiles.yml
    DBHOST: ${SOM_JARDINER_DB_HOST}
    DBPORT: ${SOM_JARDINER_DB_PORT}
    DBUSER: ${SOM_JARDINER_DB_USER}
    DBPASSWORD: ${SOM_JARDINER_DB_PASSWORD}
    DBNAME: ${SOM_JARDINER_DB_DBNAME}

version: "3.7"
services:
  builder:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-builder:${SOMENERGIA_DOCKER_TAG-latest}"
    deploy:
      replicas: 0 # never start service, since it is only for build purposes
    build:
      context: ./
      dockerfile: docker/main/Dockerfile
      target: builder
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-builder:${SOMENERGIA_DOCKER_TAG-latest}"
  main:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-main:${SOMENERGIA_DOCKER_TAG-latest}"
    deploy:
      replicas: 0 # never start service, since it is only for build purposes
    build:
      context: ./
      dockerfile: docker/main/Dockerfile
      target: main
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-main:${SOMENERGIA_DOCKER_TAG-latest}"
    environment:
      - SOMENERGIA_PROJECT_ENVIRONMENT=${SOMENERGIA_PROJECT_ENVIRONMENT?Not defined}
  dev:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-main-dev:${SOMENERGIA_DOCKER_TAG-latest}"
    build:
      context: ./
      dockerfile: docker/main/Dockerfile
      target: dev
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-main-dev:${SOMENERGIA_DOCKER_TAG-latest}"
    environment:
      <<: *dbt-common-env
    volumes:
      - *repo-common-volumes
      - python_venv_dev:/repo/.venv # mount virtualenv at /venv. See https://stackoverflow.com/a/74015989/5819113
    command: /bin/sh -c "sleep infinity" # keep container running
    networks:
      - db_nw
  dbt-deps:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-dbt-deps:${SOMENERGIA_DOCKER_TAG-latest}"
    deploy:
      replicas: 0
    build:
      context: ./
      dockerfile: docker/main/Dockerfile
      target: dbt-deps
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-dbt-deps:${SOMENERGIA_DOCKER_TAG-latest}"
    environment:
      <<: *dbt-common-env
    volumes:
      - *repo-common-volumes
      - python_venv_dbt_deps:/repo/.venv # mount virtualenv at /venv. See https://stackoverflow.com/a/74015989/5819113
  dbt-docs:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-dbt-deps:${SOMENERGIA_DOCKER_TAG-latest}"
    build:
      context: ./
      dockerfile: docker/main/Dockerfile
      target: dbt-deps
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-dbt-deps:${SOMENERGIA_DOCKER_TAG-latest}"
    environment:
      <<: *dbt-common-env
    volumes:
      - *repo-common-volumes
      - python_venv_dbt_deps:/repo/.venv # mount virtualenv at /venv. See https://stackoverflow.com/a/74015989/5819113
    command: bash -c "dbt docs generate --project-dir dbt_jardiner && dbt docs serve --project-dir dbt_jardiner --port 8050"
    ports:
      - 8050:8050

networks:
  db_nw:
    name: db_nw
volumes:
  python_venv_dev:
  python_venv_dbt_deps:
