[tool.poetry]
name = "jardiner"
version = "0.1.0"
description = ""
authors = ["pol <pol.monso@somenergia.coop>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
dbt-postgres = "^1.2.2"
sqlalchemy = "^1.4.41"
pendulum = "^2.1.2"
typer = "^0.6.1"
python-dotenv = "^0.21.0"
pandas = "^1.5.0"
requests = "^2.28.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
mkdocs = "^1.4.0"
pymdown-extensions = "^9.6"
mkdocs-material = "^8.3.0"
ipdb = "^0.13.9"
deptry = "^0.6.3"
dbt-osmosis = "^0.9.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# ignore until dbt-utils fixes pytest conf must be in root
[tool.pytest.ini_options]
addopts = "--ignore=dbt_jardiner/dbt_packages"
