version: 2

models:
  - name: raw_plantmonitordb_satellite_readings__solargis
    columns:
      - name: time
        description: timestamp del registre, des de font original sense transformacions
        tests:
          - not_null
      - name: plant
        description: id de la planta, des de font original sense transformacions
        tests:
          - not_null
      - name: global_horizontal_irradiation_wh_m2
        description: irradiació global horitzontal en wh/m2, des de font original sense transformacions
        tests:
          - not_null
      - name: global_tilted_irradiation_wh_m2
        description: irradiació global inclinada en wh/m2, des de font original sense transformacions
        tests:
          - not_null
      - name: module_temperature_dc
        description: temperatura del mòdul en ºC, des de font original sense transformacions
      - name: photovoltaic_energy_output_wh
        description: sortida d'energia fotovoltaica en wh, des de font original sense transformacions
        tests:
          - not_null
      - name: source
        description: font d'on s'ha obtingut la lectura, des de font original sense transformacions
        tests:
          - not_null
      - name: request_time
        description: timestamp de quan es va fer la sol·licitud de dades, des de font original sense transformacions
        tests:
          - not_null
