---
dbt_jardiner:
    outputs:
        prod:
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_prod

        pre:
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_pre

    target: pre

elementary:
    outputs:
        prod:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_prod_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds
        pre:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_pre_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds

config:
    send_anonymous_usage_stats: false
