---
dbt_jardiner:
    outputs:
        # needed for airbyte to pick up the correct profile during dbt transformations, see https://github.com/airbytehq/airbyte/issues/12465
        normalize:
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_prod

        prod: # used in production
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_prod

        pre: # pre-production, not used at the moment
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_pre

        test: # used during CI
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_test

        dev: # used during local development
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_dev

    target: dev

elementary:
    outputs:
        prod:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_prod_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds
        pre:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_pre_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds
        test:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_test_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds
        dev:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_dev_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds

config:
    send_anonymous_usage_stats: false
