---
dbt_jardiner:
    outputs:
        # needed for airbyte to pick up the correct profile during dbt transformations, see https://github.com/airbytehq/airbyte/issues/12465
        normalize:
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_prod

        # used in production
        prod:
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_prod

        # pre-production, not used at the moment
        pre:
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_pre

        # used during CI
        test:
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_test

        # used during local development
        dev:
            type: postgres
            threads: 1
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: dbt_dev

    target: dev

elementary:
    outputs:
        prod:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_prod_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds
        pre:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_pre_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds
        test:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_test_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds
        dev:
            type: "postgres"
            host: "{{ env_var('DBHOST') }}"
            port: "{{ env_var('DBPORT') | as_number }}"
            user: "{{ env_var('DBUSER') }}"
            password: "{{ env_var('DBPASSWORD') }}"
            dbname: "{{ env_var('DBNAME') }}"
            schema: "dbt_dev_elementary"
            threads: 4
            keepalives_idle: 0  # default 0 seconds
            connect_timeout: 10  # default 10 seconds

