dbt_jardiner:
  outputs:
    pro:
      type: postgres
      threads: 1
      host: "{{ env_var('DBHOST') }}"
      port: "{{ env_var('DBPORT') | as_number }}"
      user: "{{ env_var('DBUSER') }}"
      password: "{{ env_var('DBPASSWORD') }}"
      dbname: "{{ env_var('DBNAME') }}"
      schema: prod

    pre:
      type: postgres
      threads: 1
      host: "{{ env_var('DBHOST') }}"
      port: "{{ env_var('DBPORT') | as_number }}"
      user: "{{ env_var('DBUSER') }}"
      password: "{{ env_var('DBPASSWORD') }}"
      dbname: "{{ env_var('DBNAME') }}"
      schema: dbt_pre

  target: pre

config:     
   send_anonymous_usage_stats: False 
