version: 2
models:

  - name: alert_inverter_zero_power_at_daylight
    description: "Inverter 1h without power during daylight"

  - name: alert_string_low_intensity_at_daylight
    description: "Triggered if intensity is <=0.5A at daylight. Reports stringbox name if it's a stringbox"

  - name: alert_inverter_temperature
    description: "temperature >55 during >2h"

  - name: alert_inverter_interinverter_relative_temperature
    description: "inverter temperature > 40 AND difererence between inverters tempretarure > 10"

  - name: alert_meter_no_energy
    description: "Energy is zero during N hours depending on meter"

  - name: alert_meter_no_reading
    description: "No readings during more than N hours depending on meter"

  - name: alert_inverter_no_reading
    description: "No readings during more than N hours depending on plant"
