---
name: somenergia-jardiner

x-app-common:
  env_file:
    - .app.env
  volumes: &app-common-volumes
    "../../:/app" # mount current directory at /app

x-dbt-common:
  # reusable bits, see https://docs.docker.com/compose/compose-file/10-fragments/
  environment: &dbt-common-env # needed for ~/.dbt/profiles.yml
    DBHOST: ${SOM_JARDINER_DB_HOST}
    DBPORT: ${SOM_JARDINER_DB_PORT}
    DBUSER: ${SOM_JARDINER_DB_USER}
    DBPASSWORD: ${SOM_JARDINER_DB_PASSWORD}
    DBNAME: ${SOM_JARDINER_DB_DBNAME}

version: "3.7"
services:
  builder:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-builder:latest"
    deploy:
      replicas: 0 # never start service, since it is only for build purposes
    build:
      context: ../../
      dockerfile: containers/app/Dockerfile
      target: builder
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-builder:latest"
  app:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-app:latest"
    deploy:
      replicas: 0 # never start service, since it is only for build purposes
    build:
      context: ../../
      dockerfile: containers/app/Dockerfile
      target: app
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-builder:latest"
        - "harbor.somenergia.coop/dades/somenergia-jardiner-app:latest"
    environment:
      - SOMENERGIA_PROJECT_ENVIRONMENT=${SOMENERGIA_PROJECT_ENVIRONMENT?Not defined}
  app-dev:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-app-dev:latest"
    build:
      context: ../../
      dockerfile: containers/app/Dockerfile
      target: dev
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-builder:latest"
        - "harbor.somenergia.coop/dades/somenergia-jardiner-app-dev:latest"
    environment:
      <<: *dbt-common-env
    volumes:
      - *app-common-volumes
      - python_venv_app_dev:/app/.venv # mount virtualenv at /venv. See https://stackoverflow.com/a/74015989/5819113
    command: /bin/sh -c "sleep infinity" # keep container running
    networks:
      - db_nw
  dbt-docs:
    image: "harbor.somenergia.coop/dades/somenergia-jardiner-dbt-docs:latest"
    build:
      context: ../../
      dockerfile: containers/app/Dockerfile
      target: dbt-docs
      cache_from:
        - "harbor.somenergia.coop/dades/somenergia-jardiner-builder:latest"
        - "harbor.somenergia.coop/dades/somenergia-jardiner-dbt-docs:latest"
    depends_on:
      - app-dev
    environment:
      <<: *dbt-common-env
    volumes:
      - *app-common-volumes
      - python_venv_dbt_docs:/app/.venv # mount virtualenv at /venv. See https://stackoverflow.com/a/74015989/5819113
    command: bash -c "dbt docs generate --project-dir dbt_jardiner && dbt docs serve --project-dir dbt_jardiner --port 8050"
    ports:
      - 8050:8050

networks:
  db_nw:
    name: db_nw
volumes:
  python_venv_app_dev:
  python_venv_dbt_docs:
