version: 2

models:
  - name: forecast_best
    description: energy forecast of the previous day
    tests:
      - dbt_utils.unique_combination_of_columns:
          config:
            severity: warn
          combination_of_columns:
            - forecast_date
            - plant