html: >
  <table class="styled-table">
    <thead>
      <tr>
        <th> Nom planta</th>
        <th> Provincia</th>
        <th> Tecnologia</th>
        <th> Potència pic [kWp]</th>
        <th> Potència nominal [kW] </th>
        <th> Irradiància temps de lectura</th>
        <th> Irradiància [W/m2] </th>
        <th> Potència instantània temps de lectura</th>
        <th> Potència instantània [kW]</th>
        <th> Potència instantània vs nominal [%]</th>
        <th> Energia Perduda Ahir [MWh]</th>
      </tr>
    </thead>
    <tbody>
    {{#each data}}
      <tr>
        <td>{{ nom_planta }}</td>
        <td>{{ provincia }}</td>
        <td>{{ tecnologia }}</td>
        <td>{{ potencia_pic_kw }}</td>
        <td>{{ potencia_nominal_kw }}</td>
        <td>{{ irradiancia_ts }}</td>
        <td>{{ irradiancia_w_m2 }}</td>
        <td>{{ potencia_inst_ts }}</td>
        <td>{{ potencia_inst_kw }}</td>
        <td>{{#if  potencia_inst_vs_nominal}}<span> {{ potencia_inst_vs_nominal }}% </span><progress value="{{ potencia_inst_vs_nominal}}" max="100"> </progress>{{/if}}</td>
        <td>{{ energia_perduda_ahir_mwh }}</td>
      </tr>
    {{/each}}
    </tbody>
  </table>

css: >
  .styled-table {
      border-collapse: collapse;
      margin: 25px 0;
      font-size: 0.9em;
      /*font-family: sans-serif;*/
      min-width: 400px;
      width: 100%;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
  }
  .styled-table thead tr {
      background-color: #009879;
      color: #ffffff;
      text-align: left;
  }
  .styled-table th {
      padding: 10px 15px;
      text-align: center;
  }
  .styled-table td {
      padding: 10px 15px;
  }
  .styled-table tbody tr {
      border-bottom: 1px solid #dddddd;
  }
  .styled-table tbody tr:nth-of-type(even) {
      background-color: #f3f3f3;
  }
  .styled-table tbody tr:last-of-type {
      border-bottom: 2px solid #009879;
  }

