version: "3"


services:
  s3www:
    image: maymeow/s3www:latest
    command:
      - "-endpoint=${SOMENERGIA_EDR_S3_HOST-https://minio.somenergia.coop}"
      - "-accessKey=${SOMENERGIA_EDR_S3_ACCESS_KEY-som-jardiner-elementary-reports}"
      - "-secretKey=${SOMENERGIA_EDR_S3_SECRET_KEY?Secret key not set}"
      - "-bucket=${SOMENERGIA_EDR_S3_BUCKET_NAME-jardiner_edr_reports}"
      - "-address=0.0.0.0:${SOMENERGIA_EDR_S3_WWW_PORT-8080}"
    restart: unless-stopped
    ports:
     - "3000:${SOMENERGIA_S3_WWW_PORT-8080}"
