version: 2

sources:
  - name: plantmonitor_legacy
    schema: prod
    tags: [historicalerts]
    tables:
        - name: alert_inverter_zero_power_at_daylight_historic
        - name: alert_inverter_interinverter_relative_temperature_historic
        - name: alert_inverter_temperature_historic
        - name: alert_meter_no_readings_historic
        - name: alert_meter_zero_energy_historic
        - name: alert_inverter_zero_power_at_daylight_status
        - name: alert_inverter_interinverter_relative_temperature_status
        - name: alert_inverter_temperature_status
        - name: alert_meter_no_readings_status
        - name: alert_meter_zero_energy_status

models:

  - name: alerts_historic
    description: union of all notified alerts tables
    config:
      tags: historicalerts

  - name: alert_inverter_zero_power_at_daylight
    description: "Inverter 1h without power during daylight"

  - name: alert_string_low_intensity_at_daylight
    description: "Triggered if intensity is <=0.5A at daylight. Reports stringbox name if it's a stringbox"

  - name: alert_inverter_temperature
    description: "temperature >55 during >2h"

  - name: alert_inverter_interinverter_relative_temperature
    description: "inverter temperature > 40 AND difererence between inverters tempretarure > 10"

  - name: alert_meter_zero_energy
    description: "Energy is zero during N hours depending on meter"

  - name: alert_meter_no_readings
    description: "No readings during more than N hours depending on meter"
