version: 2

seeds:
  - name: modbus_registries_selected_meta
    description: Correspondence between modbus reading tuples and device-metric
    notes: https://docs.google.com/spreadsheets/d/1c9mdfauouESDz_LB995RnonyT9H6Uo-XpbVFlPxuJLY/edit#gid=313475710
  - name: alert_inverterregistry_clean_last_hour_temperature_sample