version: 2

seeds:
  - name: modbus_registries_selected_meta
    description: Correspondence between modbus reading tuples and device-metric (TODO register_name represents device and metrics)
    notes: https://docs.google.com/spreadsheets/d/1c9mdfauouESDz_LB995RnonyT9H6Uo-XpbVFlPxuJLY/edit#gid=313475710
  - name: alert_inverterregistry_clean_last_hour_temperature_sample
  - name: plant_topic_association
  - name: signal_device_relation
    description:
      Conté la relació entre signal_description de l'API de DSET (un UUID
      imputat per nosaltres en el document de maping que se'ls envia) amb un device_uuid
      també imputat per nosaltres que es correspon amb la columna homònima de la taula
      d'aparell que correspongui ja sigui inverter, string, sensor, plant, etc.
      Aquesta taula equival al 'seed' data/signal_device_relation.csv que es carrega
      a la taula utilitzant l'script scripts/file_to_sql.py.
      Exemple del maping enviat per [Llanillos](https://docs.google.com/spreadsheets/d/1op_WHvGZNyDdkBD7EOXK-CPU5-aGjK3r/edit#gid=629299947)
    config:
      column_types:
        device_uuid: UUID
        signal_uuid: UUID
    columns:
      - name: plant
        description: Plant name
      - name: signal
        description: Nom humà de referència per identificar l'UUID. No es fa servir al pipe
      - name: signal_uuid
        description:
          UUID del senyal present a la columns signal_UUID del maping. Es assignada manualment amb
          cada nou mapeig de GA.
        tests:
          - unique
      - name: device
        description: Nom humà per identificar l'aparell. Típicament és `device_type`+num
      - name: device_uuid
        description:
          imputat per nosaltres que es correspon amb la columna homònima de la
          taula d'aparell que correspongui ja sigui inverter, string, sensor, plant, etc.
      - name: device_type
        description: tipo de aparell (meter, inverter, sensor, plant, string)
        tests:
          - accepted_values:
              values: ['meter', 'inverter', 'sensor', 'plant', 'string', 'module']
      - name: device_parent
        description: device parent del device. e.g. un string té l'inversor1 com a pare
