FROM squidfunk/mkdocs-material:latest

# Install dependencies
# requirements is relative to the root of the repository
COPY poetry-mkdocs-requirements.txt .
RUN pip install --no-cache-dir -r poetry-mkdocs-requirements.txt